In [5]:
#we will evaluate 3 diff classifiers now so import them
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits= load_digits()

In [13]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test= train_test_split(digits.data,digits.target,test_size=0.3)

In [14]:
#1st classifier ,measure its score
lr= LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9462962962962963

In [15]:
svm= SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [16]:
rf= RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9648148148148148

In [19]:
#see using train_test_split method when we rerun all models 
#change their scores soooo..we need to rerun them multiple
#times inorder to evaluate so use KFold
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf




KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
#to simplify we'll write a generic method that takes model as an inout
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [27]:
#we can use this model to know score of diff models
get_score(SVC(),X_train,X_test,y_train,y_test)

0.987037037037037

In [32]:
#lets use kfold on digits dataset
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

In [37]:
#lets prepare scores of each model
scores_l=[]
scores_svm= []
scores_rf= []

for train_index,test_index in kf.split(digits):
    X_train,X_test,y_train,y_test= digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
    

In [38]:
scores_l

[0.0, 0.0, 0.0]

In [39]:
scores_svm


[0.0, 0.0, 0.0]

In [41]:
scores_rf

[0.0, 0.0, 0.0]

In [42]:
from sklearn.datasets import load_digits
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

digits = load_digits()
kf = KFold(n_splits=4)

def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    # 🔄 Scaling (very important!)
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    scores_l.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

print("Logistic Regression scores:", scores_l)
print("SVM scores:", scores_svm)
print("Random Forest scores:", scores_rf)


Logistic Regression scores: [0.9288888888888889, 0.9220489977728286, 0.9599109131403119, 0.9153674832962138]
SVM scores: [0.9644444444444444, 0.933184855233853, 0.9643652561247216, 0.9532293986636972]
Random Forest scores: [0.9355555555555556, 0.9265033407572383, 0.977728285077951, 0.933184855233853]


In [43]:
from sklearn.model_selection import cross_val_score

In [44]:
#shortcut function to do KFold split and estimate score of each fold for given model
cross_val_score(LogisticRegression(),digits.data,digits.target)


C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modul

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [46]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [48]:
cross_val_score(RandomForestClassifier(n_estimators= 50),digits.data,digits.target)


array([0.94166667, 0.89166667, 0.95264624, 0.95543175, 0.92479109])

In [50]:
 cross_val_score(RandomForestClassifier(n_estimators= 150),digits.data,digits.target)


array([0.93333333, 0.90833333, 0.95821727, 0.96657382, 0.92200557])

In [51]:
 cross_val_score(RandomForestClassifier(n_estimators= 100),digits.data,digits.target)


array([0.925     , 0.9       , 0.95543175, 0.96935933, 0.91643454])

In [52]:
 cross_val_score(RandomForestClassifier(n_estimators= 10),digits.data,digits.target)


array([0.89722222, 0.83611111, 0.91643454, 0.93593315, 0.87743733])

In [53]:
 cross_val_score(RandomForestClassifier(n_estimators= 30),digits.data,digits.target)


array([0.925     , 0.90277778, 0.95543175, 0.95543175, 0.92200557])