In [28]:
import pandas as pd
import numpy as np

In [30]:
df= pd.read_csv("emailspam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [31]:
df.Category.value_counts()

Category
ham               4825
spam               747
{"mode":"full"       1
Name: count, dtype: int64

In [32]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)


In [33]:
df.shape

(5573, 3)

In [34]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [36]:
X_train.shape

(4458,)

In [37]:
X_test.shape

(1115,)

In [38]:
type(X_train)

pandas.core.series.Series

In [39]:
X_train[:4]

2052    Hey darlin.. i can pick u up at college if u t...
137                    He is there. You call and meet him
1397                             Shall i start from hear.
1905    Wah... Okie okie... Muz make use of e unlimite...
Name: Message, dtype: object

In [40]:
#CREATING BAG OF WORDS USING CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59367 stored elements and shape (4458, 7697)>

In [41]:
X_train_cv.toarray()[:2][0]


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
X_train_cv.shape


(4458, 7697)

In [43]:
v.vocabulary_

{'hey': 3385,
 'darlin': 2152,
 'can': 1618,
 'pick': 5160,
 'up': 7137,
 'at': 1109,
 'college': 1879,
 'if': 3566,
 'tell': 6710,
 'me': 4359,
 'wen': 7402,
 'where': 7428,
 'mt': 4574,
 'love': 4186,
 'pete': 5128,
 'xx': 7603,
 'he': 3331,
 'is': 3713,
 'there': 6787,
 'you': 7657,
 'call': 1596,
 'and': 954,
 'meet': 4377,
 'him': 3400,
 'shall': 6020,
 'start': 6397,
 'from': 2985,
 'hear': 3341,
 'wah': 7301,
 'okie': 4872,
 'muz': 4613,
 'make': 4282,
 'use': 7172,
 'of': 4841,
 'unlimited': 7125,
 'haha': 3260,
 'men': 4397,
 'always': 925,
 'needs': 4680,
 'beautiful': 1269,
 'intelligent': 3669,
 'caring': 1648,
 'loving': 4196,
 'adjustable': 806,
 'cooperative': 1992,
 'wife': 7456,
 'but': 1566,
 'the': 6771,
 'law': 4002,
 'allows': 911,
 'only': 4894,
 'one': 4888,
 'still': 6434,
 'havent': 3323,
 'collected': 1875,
 'dough': 2411,
 'pls': 5219,
 'let': 4047,
 'know': 3927,
 'so': 6232,
 'go': 3125,
 'to': 6891,
 'place': 5188,
 'sent': 5977,
 'it': 3723,
 'get': 3082,

In [44]:
v.get_feature_names_out()[4186]

'love'

In [45]:

X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
np.where(X_train_np[0]!=0)


(array([1109, 1618, 1879, 2152, 3385, 3566, 4186, 4359, 4574, 5128, 5160,
        6710, 7137, 7402, 7428, 7603], dtype=int64),)

In [49]:
X_train_np[0][4186]

1

In [50]:
#TRAINING Naive Bayes Model

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [51]:
X_test_cv = v.transform(X_test)


In [52]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.96      0.90      0.93       144

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [53]:

emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)