In [1]:
import numpy as np


In [2]:
reviews= ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])
#positive= 1
#negative=0

In [14]:
from tensorflow.keras.preprocessing.text import one_hot
one_hot("amazing restaurant",30)
#one hot method assigns unique numbers to words within given range(vocabulary size)
#internally keras layer will convert it to 0s and 1

[7, 3]

In [17]:
vocab_size= 30
encoded_reviews= [one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[28, 11],
 [7, 3],
 [4, 15],
 [2, 25, 15],
 [12, 25, 29],
 [8, 11],
 [13, 25, 20],
 [27, 21],
 [27, 6],
 [15, 16]]

In [18]:
#as some sentences are 3 words and other are 2 words long.
#we shall apply padding!!!
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_length= 3
padded_reviews= pad_sequences(
    encoded_reviews, maxlen= max_length, padding ='post')
padded_reviews


array([[28, 11,  0],
       [ 7,  3,  0],
       [ 4, 15,  0],
       [ 2, 25, 15],
       [12, 25, 29],
       [ 8, 11,  0],
       [13, 25, 20],
       [27, 21,  0],
       [27,  6,  0],
       [15, 16,  0]])

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
embedded_vector_size = 5
model= Sequential()
#first layer is embedding matrix layer
model.add(Embedding(vocab_size, embedded_vector_size ,
                    input_length= max_length, name="embedding"))
#second layer is flattening
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))


In [21]:
X= padded_reviews
y= sentiment


In [22]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________
None


In [23]:
model.fit(X, y, epochs=50, verbose=0)

In [24]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 138ms/step - loss: 0.6116 - accuracy: 1.0000


1.0

In [25]:
weights = model.get_layer('embedding').get_weights()[0]

In [26]:
len(weights)

30

In [27]:
weights[28]#nice

array([-0.09658077, -0.00745505, -0.06084175, -0.03826009, -0.07943359],
      dtype=float32)

In [28]:
weights[7] #amazing

array([-0.07983895, -0.07666907, -0.02398236, -0.03212759, -0.0266188 ],
      dtype=float32)

In [ ]:
#u can observe the weights of the given 
#one hot unique nos : nice and amazing have similar vectors!!